INSERT INTO direccion (carrera, calle, codigo_postal)
VALUES 
("West", "Ronda Repúplica de Argentina", "59994"),
("East", "Rambla Jalisco", "02951"),
("Northwest", "Rua Naranjo", "66879"),
("East", "Cuesta Nicolás Alejandro", "65128"),
("South", "Senda Izazaga", "69989"),
("Southeast", "Caserio Batalla de Naco", "16912"),
("Northeast", "Calle Esteban", "67602"),
("Southwest", "Apartamento Balcón de los edecanes", "88678"),
("Northeast", "Rampa Carlos Esquibel", "76831"),
("Northeast", "Carretera Evelyn Monroy", "17396"),
("South", "Poblado La viga", "30503"),
("Northeast", "Extrarradio La viga", "07010"),
("Northeast", "Camino Ximena Guadalupe", "27164"),
("South", "Extrarradio Regina", "68155"),
("Southwest", "Senda Germán Negrón", "73218"),
("North", "Chalet Yamileth", "14683"),
("North", "Colonia Guillermina", "33368"),
("Northeast", "Paseo Conchita Leiva", "70628"),
("South", "Glorieta Felipe", "28928"),
("West", "Huerta Manuela", "75219"),
("West", "Paseo Valeria Alcaraz", "47614"),
("Northeast", "Municipio Alexis Quintanilla", "64986"),
("South", "Salida Elena Otero", "52051"),
("East", "Masía Pilar", "49119"),
("East", "Salida María Luisa Figueroa", "96386"),
("South", "Prolongación Diego", "37488"),
("South", "Ferrocarril Ernesto Ponce", "11282"),
("Northwest", "Rambla Estefanía", "99099"),
("East", "Parcela Francisco I. Madero", "68834"),
("Southeast", "Masía Zoe Aguilera", "02044"),
("East", "Torrente Amores", "04246"),
("Southeast", "Rampa Anita", "42101"),
("South", "Senda Magdalena", "54231"),
("South", "Aldea Dulce María Oquendo", "14191"),
("Southwest", "Lado Joaquín León", "00949"),
("East", "Conjunto Dorotea", "67479"),
("North", "Gran Subida Coruña", "28496"),
("West", "Vía Camila", "76817"),
("Southeast", "Caserio Manzanares", "17200"),
("Northwest", "Poblado Cuahutemoc", "32129"),
("Northwest", "Huerta Naranjo", "47564"),
("Southwest", "Chalet Rosario", "18842"),
("North", "Terrenos Mariano", "27597"),
("Southeast", "Muelle La viga", "21862"),
("North", "Vía Pública Horacio", "49138"),
("North", "Manzana Leonardo", "26550"),
("Southeast", "Bajada Ana Sofía", "88180"),
("West", "Puente Balcón de los edecanes", "13965"),
("East", "Plaza Izazaga", "89705"),
("South", "Avenida Juárez", "50841");

SET FOREIGN_KEY_CHECKS=0;




INSERT INTO integrante_equipo_trabajo 
(nombre, correo, cargo,id_equipo) VALUES 
("Miguel Ángel", "Marisol16@gmail.com", "Desarrollador", 19),
("Luis Miguel", "Gabriel11@hotmail.com", "Ingeniero", 24),
("Hugo", "MaraEugenia_Lovato56@hotmail.com", "Analista", 27),
("Miguel Ángel", "Beatriz_Aranda72@gmail.com", "Técnico", 50),
("Eloisa", "Benito_Godoy@hotmail.com", "Administrador", 24),
("Adela", "Guillermina_Bustamante30@hotmail.com", "Representante", 22),
("Clara", "Manuel_Soliz@yahoo.com", "Coordinador", 16),
("Mercedes", "Carmen13@hotmail.com", "Productor", 8),
("Rosario", "Irene42@gmail.com", "Estratega", 12),
("Luis Miguel", "Julia41@hotmail.com", "Planificador", 4),
("Guadalupe", "Alberto.Crdenas33@hotmail.com", "Analista", 13),
("Eduardo", "Gabriela_Armijo45@hotmail.com", "Agente", 46),
("Mateo", "Emilia.Delgado5@hotmail.com", "Diseñador", 18),
("Teresa", "Jess44@hotmail.com", "Representante", 13),
("Miguel Ángel", "Daniel20@gmail.com", "Agente", 39),
("Claudia", "Csar.Barrera99@gmail.com", "Representante", 34),
("Josefina", "Amalia_Esquibel31@yahoo.com", "Supervisor", 9),
("Yolanda", "Barbara.Benavides11@yahoo.com", "Especialista", 40),
("Antonio", "Soledad70@hotmail.com", "Técnico", 20),
("María Elena", "Jess.Vlez@hotmail.com", "Agente", 16),
("Conchita", "Virginia_Delen14@yahoo.com", "Productor", 26),
("David", "MaraTeresa_Delacrz54@yahoo.com", "Representante", 13),
("Florencia", "Eloisa78@hotmail.com", "Especialista", 50),
("Raúl", "Ricardo86@gmail.com", "Gerente", 19),
("Teodoro", "Vicente89@yahoo.com", "Asociado", 35),
("Ignacio", "Alejandra28@gmail.com", "Ingeniero", 20),
("María", "Ariadna68@gmail.com", "Agente", 46),
("Eduardo", "Leonor_Cant45@yahoo.com", "Técnico", 14),
("Cristián", "Csar.Nez12@hotmail.com", "Asistente", 31),
("Marcos", "Catalina_Escobar24@gmail.com", "Asistente", 5),
("Gonzalo", "Emilio81@yahoo.com", "Oficial", 24),
("Julia", "Luisa.Marrero@gmail.com", "Funcionario", 42),
("Mónica", "Octavio57@hotmail.com", "Diseñador", 5),
("Mayte", "Teresa.Hinojosa36@hotmail.com", "Desarrollador", 13),
("Claudio", "Federico45@gmail.com", "Arquitecto", 26),
("Berta", "Diego6@hotmail.com", "Coordinador", 45),
("Octavio", "Jess.Sierra95@yahoo.com", "Ingeniero", 35),
("Jacobo", "Ana_Murillo@gmail.com", "Desarrollador", 18),
("Cecilia", "Conchita37@yahoo.com", "Estratega", 35),
("Mónica", "Eloisa.Amador@gmail.com", "Arquitecto", 46),
("Sara", "Dolores32@yahoo.com", "Asistente", 24),
("María", "Guillermina.Rivera@yahoo.com", "Técnico", 1),
("José", "Guillermo85@gmail.com", "Diseñador", 27),
("Manuela", "Manuel_Alejandro@yahoo.com", "Facilitador", 40),
("Luis Miguel", "Micaela.Durn@gmail.com", "Especialista", 50),
("Alejandra", "Dolores.Balderas@gmail.com", "Especialista", 47),
("Magdalena", "Virginia.vila@yahoo.com", "Oficial", 38),
("Germán", "Andrs25@hotmail.com", "Diseñador", 21),
("Mónica", "Arturo.Guevara@gmail.com", "Ingeniero", 9),
("Alejandro", "Mariano.Leyva@yahoo.com", "Agente", 35);

INSERT INTO equipo_trabajo (
    cargo
) VALUES
("Identidad"),
("Mobilidad"),
("Calidad"),
("Comunicaciones"),
("Calidad"),
("Soluciones"),
("Intranet"),
("Usabilidad"),
("Integración"),
("Paradigma"),
("Datos"),
("Marketing"),
("Calidad"),
("Seguro"),
("Identidad"),
("Mercados"),
("Marca"),
("Seguro"),
("Implementación"),
("Programa"),
("Usabilidad"),
("Operaciones"),
("Identidad"),
("Métricas"),
("Grupo"),
("Soluciones"),
("Mercados"),
("Mobilidad"),
("Integración"),
("Mercados"),
("Mercados"),
("Factores"),
("Identidad"),
("Investigación"),
("Cuentas"),
("Calidad"),
("Seguro"),
("Programa"),
("Seguro"),
("Mercados"),
("Creativo"),
("Cuentas"),
("Web"),
("Respuesta"),
("Mobilidad"),
("Optimización"),
("Normas"),
("Respuesta"),
("Métricas"),
("Respuesta"); 


INSERT INTO sede (nombre, correo, numero, id_equipo_trabajo)
VALUES 
('palmira', 'palmira1@unal.edu.co', '1234567890', 10),
('paz', 'paz@unal.edu.co', '2345678901', 17),
('bogota', 'bogota@unal.edu.co', '3456789012', 42),
('medellin', 'medellin@unal.edu.co', '4567890123', 16);

INSERT INTO proyecto (nombre, descripcion, fecha, id_sede ,id_equipo_trabajo, id_direccion)
VALUES 
("nacional factores productor", "Corporis a optio laboriosam non similique. Aut perferendis a reprehenderit temporibus officia quam quaerat nulla. Accusamus recusandae consequatur repudiandae facere velit occaecati itaque voluptate illum. Itaque harum adipisci veniam porro. Labore perspiciatis autem sit eveniet enim sed quo eveniet architecto.", "2022-11-20", "1", "23", "4"),
("Jefe Calidad Oficial", "Cumque sed reiciendis perspiciatis deleniti. Consequuntur suscipit ratione in fugit quo error magnam aut. Velit accusamus officia maiores.", "2022-09-03", "2", "27", "2"),
("Director Intranet Representante", "Ad nostrum neque. Quidem ratione ut quae provident earum iste a possimus maiores. Recusandae saepe nam.", "2022-08-31", "2", "48", "2"),
("Regional Soluciones Supervisor", "Cum eius illum eum tempora perferendis eveniet autem est. Recusandae nihil iusto deserunt dicta quod. Aliquam aliquid ea doloremque. Laudantium cupiditate consectetur sed. Aliquid rerum neque adipisci delectus quo non. Non odit facere nesciunt dignissimos sed neque voluptates.", "2023-04-26", "1", "3", "1"),
("Futuro Calidad Especialista", "Dolorem commodi pariatur iure sapiente ullam incidunt. Voluptatum facilis ea iure earum quod nobis nihil repudiandae quaerat. Animi amet voluptate unde aliquam quod.", "2023-05-27", "3", "24", "3"),
("Humano Marketing Asociado", "Optio repellendus cumque. Cumque ullam deserunt aut reiciendis nobis explicabo molestiae omnis. Odit aut rerum.", "2022-11-19", "4", "25", "4"),
("Senior Programa Director", "Nemo perspiciatis cupiditate perferendis odio nihil rem autem harum. Voluptatibus corrupti sunt. Eum explicabo numquam placeat tempore sit aspernatur. Officia maxime neque quia architecto tempora. Placeat debitis minus fuga commodi expedita.", "2023-01-01", "1", "33", "1"),
("Distrito Web Supervisor", "Repellendus aliquam eveniet fugit pariatur maxime. Nulla modi asperiores porro ipsum eligendi. Provident minima architecto quidem inventore. Itaque non quis natus esse. Sit laborum consequuntur eos exercitationem pariatur aspernatur ad. Occaecati consectetur possimus neque alias voluptatem debitis nulla ipsam cupiditate.", "2022-06-17", "1", "18", "1"),
("Dinánmico Integración Asociado", "Velit earum at nisi in consequatur occaecati itaque quo nesciunt. Nemo vero explicabo inventore ea consequatur corporis expedita iusto porro. Nobis quod ipsum dolor numquam quis repudiandae. Voluptatum suscipit autem quos ipsum.", "2022-07-07", "2", "2", "2"),
("Adelante Factores Arquitecto", "Quibusdam exercitationem iure quam deserunt similique. Aliquam reiciendis quaerat asperiores eaque illum ut. Reiciendis magni tempore exercitationem soluta nihil iste. Cum culpa reprehenderit vel veniam adipisci aliquam. Ullam error ex libero. Nisi eveniet dolores expedita explicabo ad vero velit nisi magni.", "2023-03-20", "1", "15", "1"),
("Humano Normas Director", "Repellat sed sed inventore optio. Nobis inventore sint quisquam natus aliquid quis cupiditate. Aut quidem vero reiciendis ullam minima ad aut beatae. Ullam nihil nemo neque. Deserunt harum ullam laboriosam occaecati iure a assumenda. Ab hic consequuntur placeat optio blanditiis minima repellendus cum a.", "2022-07-19", "1", "23", "1"),
("Regional Marca Asistente", "Rem tenetur quia facere tenetur omnis doloribus iste pariatur magnam. Rem maiores error dicta voluptatum minima minus. Eum magnam minima eaque quasi aperiam ab. Magni quam magnam fuga assumenda atque facilis rem ipsum ipsum. Perferendis autem molestiae eveniet odit dignissimos facilis cumque vel aspernatur. Repellendus sequi quidem.", "2022-12-02", "4", "12", "4"),
("Producto Aplicaciones Agente", "Quas voluptas placeat quos vitae ducimus officiis suscipit libero nostrum. Aperiam aut incidunt rem saepe quod illum alias. Iusto perspiciatis neque similique. Minus eveniet dicta recusandae est ab ea enim.", "2023-01-08", "4", "10", "4"),
("Senior Aplicaciones Estratega", "Consectetur consequuntur amet libero sed quae explicabo sit vitae. Exercitationem unde odio dolore ad eveniet. Enim voluptas totam ab distinctio autem quam.", "2022-07-12", "1", "5", "1"),
("Dinánmico Intranet Asistente", "Tempore hic architecto illum ex culpa. Maiores maxime rerum dolorem. Tempora perferendis eos in provident mollitia natus. Mollitia quidem ad cumque deleniti.", "2022-10-31", "3", "39", "3"),
("Regional Soluciones Productor", "Cum ea veritatis aut fuga est iure corrupti. Fugit explicabo suscipit suscipit. Amet voluptatum fuga. Quas quasi nostrum recusandae dolor. Est ab autem aliquam quia voluptatem reiciendis dolores est asperiores. Omnis occaecati quaerat eaque vero maiores aliquid ad.", "2023-01-11", "3", "48", "3"),
("Gerente División Supervisor", "Eos expedita quibusdam. Voluptas eum numquam. Exercitationem neque voluptatibus exercitationem nobis est aspernatur recusandae architecto. Impedit quia neque asperiores saepe autem officia cum illum. Sunt tenetur numquam perferendis quia ad eos. Nulla quas nobis accusamus ullam.", "2023-05-19", "4", "1", "4"),
("Dinánmico Funcionalidad Facilitador", "Blanditiis dignissimos culpa consectetur perspiciatis voluptatibus ullam laborum mollitia vitae. Incidunt aut esse placeat mollitia. Animi commodi perspiciatis iure. Labore sapiente cumque excepturi recusandae exercitationem inventore. Quas libero voluptates sequi perspiciatis dolorum consequatur.", "2022-06-30", "1", "24", "1"),
("Jefe Interacciones Desarrollador", "Fuga est veritatis quidem quam alias illo eveniet a. Fugiat itaque est deleniti. Dolorum rem praesentium ipsum iusto.", "2022-06-13", "1", "45", "1"),
("Interno Comunicaciones Estratega", "Voluptatum optio ut iste quia aperiam quam occaecati. Eligendi voluptas sapiente libero reiciendis quos itaque. In sapiente nostrum facere quas incidunt magnam sequi id consequuntur. Rem explicabo eos porro fuga sunt possimus fuga iure laborum. Excepturi optio exercitationem tenetur eaque maiores non harum id quisquam.", "2023-01-12", "3", "2", "3"),
("Heredado Operaciones Agente", "Blanditiis ullam inventore voluptate qui qui excepturi error pariatur. Soluta ad rerum facere. Consequuntur laudantium illo sint mollitia impedit placeat nulla iste. Explicabo tempore consequuntur sint porro.", "2022-10-30", "3", "49", "3"),
("Jefe Interacciones Administrador", "Ipsum eos tempore quos corporis commodi similique vero debitis. Dolorum ex ducimus reiciendis. Quos aspernatur est voluptates veniam earum quis at. Placeat qui numquam ullam sunt. Libero commodi accusamus exercitationem nobis nobis voluptates accusantium quia tempore.", "2023-03-20", "4", "12", "4"),
("Inversor Infraestructura Funcionario", "Atque autem recusandae dolorum necessitatibus ut suscipit. At quaerat adipisci culpa blanditiis possimus non cum in. Commodi molestiae voluptatibus facilis expedita sit ut iste.", "2023-01-24", "1", "27", "1"),
("Director Soluciones Administrador", "Accusamus animi atque ad voluptate itaque consequuntur sit quisquam in. Cumque temporibus blanditiis recusandae amet enim totam. Perferendis nihil veniam facilis veniam illum. Illum explicabo magnam dolore dignissimos minima eius culpa.", "2023-04-26", "2", "9", "2"),
("Futuro Grupo Agente", "Nisi perferendis similique ex dolore natus facere est. Ut modi repudiandae perferendis fuga eum expedita. Deserunt suscipit necessitatibus doloremque modi explicabo.", "2022-08-05", "3", "39", "3"),
("Regional Integración Desarrollador", "Alias dolorem libero aspernatur odit reprehenderit exercitationem magnam. Libero labore molestias perferendis sapiente. Qui provident repellat error. Ipsum pariatur architecto aperiam deserunt deserunt. Tempore aspernatur culpa suscipit voluptatum earum officiis soluta.", "2023-04-27", "3", "17", "3"),
("Gerente Marketing Relacciones", "Officiis velit saepe. Perspiciatis aperiam impedit ad veniam. Nulla numquam voluptatibus ducimus voluptatibus deleniti. Natus sapiente tenetur esse ut ipsa. Sunt earum minus odit temporibus magnam perspiciatis. Error recusandae tempora eveniet voluptatem vitae.", "2022-10-06", "1", "48", "1"),
("Jefe Web Supervisor", "Facere ut numquam illum perspiciatis. Nam accusamus at error quod repellat. Quibusdam est praesentium magni quos unde error. Minima in harum quos voluptates eum praesentium cum repellendus.", "2023-02-28", "2", "7", "2"),
("Global Factores Analista", "Dolorum placeat molestiae autem officia error. Sint atque nemo. Officia soluta accusantium voluptatum perferendis quisquam. Esse aperiam esse laudantium totam rem fugiat modi. Voluptatum minus neque occaecati rerum dolor.", "2023-03-27", "4", "35", "4"),
("Interno Factores Productor", "Unde reiciendis harum quas. Reprehenderit ipsum itaque. Reiciendis dignissimos quod. Qui beatae dolores nulla nam mollitia.", "2022-12-24", "4", "2", "4"),
("Heredado Funcionalidad Director", "Ipsam corrupti reiciendis nisi iusto illo aliquid. Cum cum quasi ut omnis temporibus earum accusantium nostrum. Repellat ipsa nam est soluta mollitia consequuntur. Repudiandae aspernatur architecto vitae expedita earum odit aperiam incidunt neque. Eaque natus alias minus quasi.", "2022-10-06", "1", "26", "1"),
("Regional Mobilidad Representante", "Amet fugit natus inventore. Odit alias eum eum. Blanditiis alias doloremque soluta repellendus esse eveniet inventore. Corrupti porro voluptatibus. Modi sapiente aliquam saepe perspiciatis officia officia voluptatibus.", "2023-05-03", "2", "42", "2"),
("Interno Contabilidad Oficial", "Quos a perferendis quos facilis iusto velit mollitia. Sit fugiat quaerat dolorum impedit facilis repellendus odio rerum. Nulla odit natus architecto voluptate. Eligendi nemo repudiandae animi eligendi incidunt.", "2022-10-17", "3", "9", "3"),
("International Comunicaciones Relacciones", "Blanditiis fugit placeat occaecati eligendi eum cumque quae a. Nihil sequi est deleniti. Eaque ratione voluptatibus minima cum. Corrupti nulla magni repudiandae voluptate. Tenetur molestiae autem tempora.", "2022-07-02", "2", "15", "2"),
("Gerente Marketing Facilitador", "Aliquam laborum perferendis provident recusandae. Quo recusandae amet reiciendis quia recusandae tenetur laborum optio vel. Iusto iusto a asperiores. Eum soluta voluptatem reprehenderit corrupti maxime delectus vero. Illo dicta sapiente in libero optio unde ullam qui qui.", "2022-09-30", "4", "37", "4"),
("Humano Infraestructura Arquitecto", "Eaque veniam quidem minima magni quo repellat laboriosam quo libero. Corrupti facilis cum pariatur. Ipsum deleniti reprehenderit cum eaque ea vitae sequi. Perspiciatis enim nobis voluptatem ipsam maiores laborum eveniet.", "2022-09-01", "1", "23", "1"),
("Producto Paradigma Funcionario", "Animi tenetur dolor ad similique perspiciatis recusandae error quaerat vero. Repellendus doloremque dolorem non alias hic. Ratione quidem totam error animi excepturi.", "2023-02-18", "1", "45", "1"),
("Dinánmico Seguro Analista", "Tempora officiis fuga quidem nesciunt numquam quis nulla. Et inventore minus voluptatum rerum eum. Aspernatur ex illum labore suscipit necessitatibus recusandae sunt cumque debitis.", "2022-06-25", "4", "25", "4"),
("Global Métricas Productor", "Excepturi sapiente debitis ipsa at aspernatur non. Facere quidem atque odio. Sunt odit autem sunt accusamus possimus ipsa possimus ullam eveniet. Molestias dolorum at similique. Nostrum voluptatem repudiandae quos occaecati doloribus. Incidunt natus accusantium ad possimus sit.", "2022-11-02", "2", "43", "2"),
("Central Usabilidad Oficial", "Amet veniam aperiam magnam excepturi optio illum. Nulla facere dolore. Consequuntur aliquam facere distinctio.", "2023-04-24", "4", "38", "4"),
("Director Aplicaciones Funcionario", "Quasi nostrum repudiandae sit totam hic. Perspiciatis quaerat id praesentium enim aperiam. Tempore quis occaecati ea enim fugiat alias. Rerum non voluptas tempore maiores quasi voluptatum numquam. Ex sunt voluptatem sint cumque sit ratione libero. Expedita dignissimos sit quibusdam.", "2022-11-17", "3", "9", "3"),
("Regional Optimización Asistente", "Nostrum debitis voluptatum a voluptatibus rem nostrum odit accusamus dolores. Perspiciatis quibusdam error. Nisi fugiat neque dolor exercitationem nisi ipsam expedita id debitis. Est ab doloremque sed.", "2022-07-27", "3", "28", "3"),
("Global Contabilidad Gerente", "Aperiam minus qui temporibus ea eaque esse perspiciatis. Excepturi ad cumque exercitationem. Nulla voluptatibus exercitationem porro laboriosam hic. Reiciendis possimus inventore quam veritatis ullam minus. Hic soluta molestias magnam incidunt natus.", "2023-01-17", "2", "12", "2"),
("Senior Grupo Gerente", "Possimus commodi eius numquam voluptatibus molestiae corporis soluta quidem. Beatae exercitationem velit repellat dolorem ducimus. Accusantium cupiditate molestias corrupti rem numquam tenetur dolor. Quam esse adipisci sequi laborum animi.", "2023-04-09", "1", "8", "1"),
("Senior Integración Analista", "Exercitationem nobis dolore deserunt. Iste error consequatur nobis rerum doloribus eligendi laboriosam nemo. Necessitatibus sed eum temporibus placeat voluptate soluta eligendi omnis laudantium. Illo non dignissimos voluptatum hic optio et. Ipsam facere sint.", "2023-05-27", "2", "44", "2"),
("Futuro Respuesta Director", "Tempore impedit eos ipsam omnis esse. Placeat ipsa enim pariatur tempora delectus. Neque provident unde magnam.", "2023-01-21", "1", "15", "1"),
("International Mercados Administrador", "Consequatur iure quisquam hic esse at. Reprehenderit voluptate repellendus inventore ipsum perspiciatis. Vitae rem quo delectus molestiae harum. Cum omnis laudantium dicta sint laudantium nesciunt unde. Sed molestiae voluptatum minima consectetur molestias. Consequuntur officiis ea sequi dolor occaecati eos incidunt.", "2023-05-19", "1", "2", "1"),
("Directo Identidad Arquitecto", "Aut reiciendis maxime. Necessitatibus quasi dolorem. Delectus magni impedit. Itaque qui temporibus blanditiis amet aliquam sunt. Vitae voluptatibus voluptates commodi sunt magnam odit adipisci.", "2023-01-27", "1", "45", "1"),
("Humano Datos Gerente", "Sed maxime dolorem odio itaque dolorem magnam. Doloremque at ipsa itaque quos. Alias et expedita animi dolore nulla. Iusto aspernatur excepturi. Doloremque dicta vero iusto harum aspernatur odio ullam. Non assumenda unde numquam repellat.", "2022-10-15", "1", "2", "1"),
("Interno Operaciones Oficial", "Et dolore quis impedit. Nam ut hic labore amet nam quae mollitia cum. Amet ipsa adipisci repellat commodi hic cumque similique quos. Consectetur natus praesentium dignissimos. Voluptatem voluptatem quisquam.", "2022-05-30", "3", "4", "3");

INSERT INTO decano(nombre, correo)
VALUES
("Elisa", "Anita97@hotmail.com"),
("Gabriela", "MaradelCarmen_Rivas@yahoo.com"),
("Patricio", "Mercedes_Gastlum74@hotmail.com"),
("Ana", "Marcela_Otero@hotmail.com"),
("Santiago", "Alejandro46@hotmail.com"),
("Elvira", "Octavio54@hotmail.com"),
("Leticia", "Eva.Carrera@gmail.com"),
("Sonia", "Ignacio65@yahoo.com"),
("Yolanda", "Clemente.Durn@gmail.com"),
("Beatriz", "Javier_Valentn53@gmail.com"),
("Rocío", "Benjamn.Ojeda90@hotmail.com"),
("Rosa", "Teresa_Mndez@gmail.com"),
("Emilio", "Maril_Paz@gmail.com"),
("Lola", "Magdalena.Castaeda@hotmail.com"),
("Rosa", "Lorenzo.Gmez12@gmail.com"),
("Bernardo", "Ana_Zarate14@gmail.com"),
("Tomás", "Mayte85@gmail.com"),
("María Soledad", "AnaLuisa.Mojica1@gmail.com"),
("Carlos", "Julia50@gmail.com"),
("Rosa", "Marisol43@gmail.com"),
("Gabriel", "Mario11@hotmail.com"),
("Rebeca", "MaraSoledad.Palomino6@hotmail.com"),
("Florencia", "Claudia_Bez84@hotmail.com"),
("Leticia", "Barbara57@gmail.com"),
("Julia", "Eduardo.Fernndez50@hotmail.com"),
("Gregorio", "Berta44@yahoo.com"),
("Débora", "Germn50@yahoo.com"),
("Lourdes", "Gerardo.Medrano64@hotmail.com"),
("María de los Ángeles", "Adela_Casanova46@yahoo.com"),
("Joaquín", "Caridad.Rico34@hotmail.com"),
("Salvador", "Rosario_Saavedra47@yahoo.com"),
("Adriana", "Gabriel.Osorio62@hotmail.com"),
("Mariano", "Sancho70@yahoo.com"),
("Juan", "Germn.Caldern@gmail.com"),
("César", "Leonor.Rosas@hotmail.com"),
("Eva", "Julio.Madrid@gmail.com"),
("Samuel", "Juana_Madrigal36@gmail.com"),
("Yolanda", "Beatriz.Delgadillo17@yahoo.com"),
("Gerardo", "Cristin69@gmail.com"),
("José", "Armando_Zambrano73@gmail.com"),
("Rosario", "Diego.Yez97@hotmail.com"),
("Manuel", "Luisa.Osorio62@gmail.com"),
("Vicente", "Fernando93@gmail.com"),
("Ana María", "Emilio60@gmail.com"),
("Isabela", "Arturo47@gmail.com"),
("Sara", "Maradelosngeles_Alcal@hotmail.com"),
("Ana", "Fernando.Jurez45@hotmail.com"),
("Ricardo", "JosMara_Delgadillo25@gmail.com"),
("Enrique", "Marisol98@hotmail.com"),
("Bernardo", "Armando.Alcaraz48@hotmail.com");

INSERT INTO profesor(nombre, correo,id_facultad)
VALUES
("Alberto", "Leticia14@gmail.com", 3),
("María Luisa", "Salvador.Pagan6@gmail.com", 2),
("Claudia", "Octavio30@hotmail.com", 6),
("Javier", "MaradelCarmen22@yahoo.com", 5),
("Guillermina", "Eva.Carrasquillo93@hotmail.com", 2),
("Cecilia", "Octavio_Ojeda47@gmail.com", 4),
("Florencia", "Elisa_Briones@yahoo.com", 7),
("Isabela", "Teresa_Villa50@hotmail.com", 8),
("Margarita", "Rodrigo78@hotmail.com", 2),
("Federico", "Natalia_Blanco14@yahoo.com", 5),
("María Cristina", "Dbora16@hotmail.com", 4),
("Carmen", "Jos_Alonzo59@gmail.com", 4),
("Lorenzo", "Adn_Lovato75@gmail.com", 8),
("María del Carmen", "Adela_Montz77@yahoo.com", 8),
("Julia", "Adn_Carrin@gmail.com", 5),
("Teresa", "Margarita.Alva@hotmail.com", 7),
("Olivia", "Manuela.Esquivel71@yahoo.com", 2),
("Marcela", "Beatriz87@gmail.com", 8),
("Ernesto", "Eduardo57@hotmail.com", 8),
("Marcos", "Guillermina.Hinojosa@gmail.com", 3),
("Ana", "Martn.Cerda81@hotmail.com", 6),
("Gonzalo", "Yolanda.Guardado5@gmail.com", 2),
("Gilberto", "Ramn5@gmail.com", 6),
("Rosalia", "Enrique_Polanco@hotmail.com", 2),
("Gustavo", "Fernando.Matas@gmail.com", 2),
("Salvador", "Felipe_Valverde@gmail.com", 3),
("Caridad", "Lola.Olvera@yahoo.com", 5),
("Ester", "Luis.Samaniego92@gmail.com", 2),
("Lola", "Leonor_Rodrguez63@yahoo.com", 1),
("José Eduardo", "Fernando.Abrego@gmail.com", 8),
("Blanca", "Josefina.Carrasquillo59@hotmail.com", 4),
("Elena", "Raquel39@gmail.com", 3),
("Caridad", "Guadalupe66@hotmail.com", 7),
("José María", "Beatriz19@hotmail.com", 4),
("Gerardo", "Florencia57@gmail.com", 6),
("Yolanda", "Homero.Olmos27@yahoo.com", 3),
("Dorotea", "Alejandra71@gmail.com", 2),
("Carlos", "Sonia.deJess@hotmail.com", 4),
("Eduardo", "MaradelCarmen.Galvn85@gmail.com", 3),
("Jerónimo", "Andrs.Roln92@gmail.com", 5),
("María Teresa", "Leticia5@gmail.com", 3),
("Hernán", "Ramn.Verduzco37@yahoo.com", 6),
("Felipe", "Isabela_Patio89@hotmail.com", 1),
("Débora", "MaradelCarmen.Olmos@gmail.com", 4),
("Esteban", "Virginia.Balderas@hotmail.com", 1),
("Elsa", "Silvia_Prieto@gmail.com", 6),
("Inés", "Esteban57@gmail.com", 7),
("Benito", "Federico.Elizondo@gmail.com", 8),
("Nicolás", "Ramiro.Velzquez84@yahoo.com", 8),
("Ángela", "Adriana.Ponce@gmail.com", 3);

INSERT INTO facultad(nombre,id_decano)
VALUES
("Ingenieria", 10),
("Ciencias Humanas", 2),
("Artes", 8),
("Ciencias", 9),
("Ciencias Economicas", 40),
("Medicina", 34),
("Odontologia", 19),
("Medicina Veterinaria y de Zootecnia", 17);


INSERT INTO servicio_ciudadania(correo, telefono)
VALUES
("servicio_ciudadania@hotmail.com", "+57 32979599");


INSERT INTO servicio_detalle_ciudadania(nombre, descripcion, id_servicio_ciudadania)
VALUES
("Proyectos de creación artística"," Son aquellos cuyo fin es producir obras artísticas y literarias como libros, obras musicales, pinturas al óleo, a la acuarela o al pastel, dibujos, grabados en madera, obras caligráficas y coreográficas, obras producidas por medio de corte, grabado, damasquinado, etc., de metal, piedra, madera u otros materiales, estatuas, relieves, esculturas, fotografías artísticas, pantomimas u otras obras coreográficas, entre otros.", 1  ),

("Extensión solidaria", "Comprende los programas y proyectos científicos, tecnológicos, artísticos y culturales de alto impacto social que se desarrollan y financian total o parcialmente con recursos de la Universidad. Por medio de esta modalidad se integran los distintos campos del conocimiento y se estrechan vínculos con diversos sectores de la sociedad en busca de la inclusión social de comunidades vulnerables", 1),

("Innovación social","A través de la Dirección Nacional de Extensión, Innovación y Propiedad Intelectual, la Universidad Nacional de Colombia apoya el desarrollo de iniciativas encaminados a facilitar un diálogo de saberes, entre el conocimiento propio de las comunidades y el sistemático generado en la academia, con el fin de que, de manera conjunta y colaborativa, se construyan soluciones a problemáticas sociales y se permita que ese conocimiento cobre sentido en cada acción cotidiana de los individuos y las comunidades del país.", 1),
("Consultorio jurídico", "A través del Consultorio Jurídico de la Universidad Nacional de Colombia se busca que las personas de escasos recursos puedan tener una respuesta adecuada a sus problemas y una atención jurídica responsable, honesta y eficaz por parte de los estudiantes de la Facultad de Derecho, Ciencias Políticas y Sociales de la sede Bogotá.", 1),

("salud y bienestar", "Servicio de salud y bienestar a la comunidad", 1);


INSERT INTO servicio_estado(correo, telefono)
VALUES
("servicio_estado@yahoo.com", "+57 36187742");

INSERT INTO servicio_detalle_estado(nombre, descripcion, id_servicio_estado)
VALUES
("Consultorías y Asesorías", "Son trabajos especializados que se realizan con el fin de entender y redefinir problemáticas existentes, al igual que encontrar y recomendar las soluciones más apropiadas en materia científica, técnica, tecnológica, política, económica, social, ambiental, artística y cultural.", 1),

("Interventorías y Conceptos", "Son los servicios relacionados con la verificación técnica, administrativa y financiera del cumplimiento de las condiciones o términos de los contratos o convenciones pactadas para la ejecución de proyectos.", 1),

("Evaluación de Programas y Políticas", "Son las actividades relacionadas con la evaluación, discusión y análisis de programas y políticas públicas.", 1),

("Proyectos Especiales y Proyectos CTeI Sistema General de Regalías", "El equipo de trabajo brinda asesorías y capacitaciones en temas metodológicos, financieros y jurídicos, en la formulación y estructuración de proyectos para ser evaluados y aprobados por el Órgano Colegiado de Administración y Decisión (OCAD) del Fondo de Ciencia, Tecnología e Innovación (FCTeI) del Sistema General de Regalías (SGR)", 1),

("Capacitaciones","Actividades correspondientes a la oferta de educación continua y permanente, para entidades públicas y privadas, con el fin de apoyar los planes institucionales de capacitación", 1),
("Políticas y Pasantías", "Su finalidad es favorecer el desarrollo profesional, social y comunitario de los y las estudiantes de pregrado y posgrado, matriculados en la Universidad, mediante la aplicación de sus conocimientos y aprendizaje en la práctica.", 1),

("Cooperación Internacional", "Comprende el conjunto de actividades de cooperación académica, científica, técnica, cultural y deportiva que adelante la Universidad en su carácter de institución pública, en el marco de estrategias nacionales de cooperación internacional, de programas internacionales oficiales de fomento a la cooperación en estos campos, o de compromisos adquiridos por el país en comisiones o acuerdos bilaterales o multilaterales de cooperación, en los que la participe la Universidad y que involucren el principio de reciprocidad.", 1);

INSERT INTO servicio_empresa(correo, telefono)
VALUES
("servicio_empresa@yahoo.com", "+57 45184342");

INSERT INTO servicio_detalle_empresa(nombre, descripcion, id_servicio_empresa )
VALUES
("Consultorías y Asesorías","Son trabajos especializados que se realizan con el fin de entender y redefinir problemáticas existentes, encontrar y recomendar las soluciones más apropiadas en materia científica, técnica, tecnológica, política, económica, social, ambiental, artística y cultural." , 1 ),

("Interventorías y Conceptos", "Son las diversas formas de participación de los docentes, en nombre de la Universidad, cuando en su calidad de expertos brindan opiniones calificadas de carácter puntual sobre temas o problemas científicos, técnicos, tecnológicos, políticos, económicos, sociales, ambientales, artísticos o culturales. Estas opiniones se pueden presentar en audiencias públicas, peritajes o testimonios.", 1),

("Proyectos de innovación y gestión tecnológica","La modalidad gestión tecnológica e innovación comprende aquellos proyectos e iniciativas que se adelanten como resultado de las labores de docencia e investigación de la comunidad académica de la Universidad Nacional de Colombia cuya finalidad incluya la transferencia de nuevo conocimiento a los procesos productivos, sociales, culturales y políticos del país.Se consideran proyectos de innovación los que buscan desarrollar e implementar un mejoramiento o nuevo valor en el corto, mediano o largo plazo. A su vez, la implementación de la innovación se refiere a la introducción en el mercado o a la aplicación y el uso del desarrollo innovador con aceptación de la sociedad.", 1),

("Prácticas y pasantías", "Su finalidad es favorecer el desarrollo profesional, social y comunitario de los estudiantes de pregrado y posgrado matriculados en la Universidad y fortalecer la relación con otros sectores, mediante la aplicación de sus conocimientos y el aprendizaje en la práctica.", 1),

("Laboratorios","Servicios de laboratorios acreditados por el Organismo Nacional de Acreditación de Colombia ONAC o el Instituto de Hidrología, Meteorología y Estudios Ambientales - IDEAM en la norma NTC-ISO/IEC 17025, ofrecidos para la realización de pruebas, ensayos o calibraciones de utilidad para la industria nacional o a la comunidad en general.", 1),

("Capacitaciones","Actividades de formación continua a la medida, para entidades públicas, privadas, organizaciones y grupos representativos de usuarios, de acuerdo con sus necesidades o requerimientos, con el fin de apoyar los planes institucionales de capacitación.", 1),

("Cooperacion internacional","Comprenden el conjunto de actividades de cooperación académica, científica, técnica, cultural y deportiva que adelante la Universidad, en su carácter de institución pública, en el marco de estrategias nacionales de cooperación internacional, de programas internacionales oficiales de fomento a la cooperación en estos campos, o de compromisos adquiridos por el país en comisiones o acuerdos bilaterales o multilaterales de cooperación, en las que la participe universidad y que involucren el principio de reciprocidad. Estas actividades contribuyen al intercambio y la transferencia de conocimientos, capacidades, experiencias y tecnologías entre países para su mutuo beneficio. Esta cooperación se debe manifestar en la resolución bilateral o multinacional de problemas compartidos.",1);





INSERT INTO modalidad(tipo_modalidad)
VALUES
("PRESENCIAL"),
("VIRTUAL");



INSERT INTO cursos_diplomados(nombre, duracion, fecha, id_profesor, id_modalidad)
VALUES ("Rústico Madera Pizza", "18:5858", "2050-05-11", 11, 2),
("Ergonómico Hormigon Zapatos", "28:3030", "2088-02-08", 12, 1),
("Increible Metal Bicicleta", "05:5151", "1998-10-04", 19, 2),
("Artesanal Madera Pescado", "41:3535", "2076-04-13", 24, 2),
("Hecho a mano Plástico Pelota", "02:3434", "2066-09-15", 27, 1),
("Sabroso Plástico Coche", "10:011", "2059-10-28", 0, 1),
("Inteligente Metal Guantes", "40:3737", "2006-11-28", 35, 1),
("Hecho a mano Metal Patatas fritas", "41:1010", "2015-06-02", 1, 2),
("Increible Ladrillo Pantalones", "46:1616", "2022-09-07", 22, 1),
("Sorprendente Algodón Bicicleta", "25:3838", "2017-10-03", 47, 2),
("Práctico Acero Pelota", "42:5454", "2075-11-25", 3, 2),
("Genérico Plástico Raton", "30:1919", "2049-12-10", 26, 2),
("Sabroso Madera Zapatos", "06:5252", "2084-07-18", 18, 2),
("Inteligente Plástico Guantes", "30:4848", "2095-08-16", 19, 1),
("Sabroso Metal Silla", "24:4343", "1991-03-31", 31, 1),
("Pequeño Metal Pantalones", "42:4141", "2013-09-20", 32, 2),
("Fantástico Hormigon Raton", "38:1616", "2012-09-11", 30, 1),
("Increible Madera Patatas fritas", "09:1616", "2067-08-14", 3, 2),
("Guapa Metal Sopa", "04:3939", "2086-06-03", 33, 1),
("Sabroso Metal Raton", "14:1212", "2009-12-14", 33, 2),
("Guapo Plástico Camiseta", "12:3939", "2016-01-02", 30, 1),
("Guapo Ladrillo Atún", "07:1212", "2055-06-03", 30, 1),
("Sorprendente Madera Bacon", "39:033", "2026-06-05", 46, 1),
("Fantástico Algodón Ensalada", "21:4343", "2076-05-17", 46, 2),
("Práctico Metal Mesa", "20:4545", "1998-04-27", 37, 2),
("Sorprendente Ladrillo Gorro", "51:5151", "2041-07-11", 35, 2),
("Rústico Plástico Raton", "35:4444", "2084-03-29", 7, 1),
("Genérico Algodón Salchichas", "43:5050", "2064-09-24", 10, 1),
("Artesanal Metal Mesa", "20:4343", "2014-12-24", 48, 2),
("Fantástico Plástico Camiseta", "24:3737", "2042-03-12", 11, 2),
("Guapo Algodón Gorro", "25:1414", "2063-07-10", 40, 1),
("Artesanal Hormigon Pelota", "45:3333", "2058-05-04", 12, 1),
("Fantástico Madera Silla", "02:1717", "1995-03-04", 10, 2),
("Fantástico Metal Mesa", "31:1616", "2088-10-24", 42, 2),
("Pequeño Metal Pizza", "48:011", "2069-09-29", 10, 2),
("Práctico Plástico Zapatos", "34:055", "1999-09-06", 43, 1),
("Sabroso Metal Pollo", "25:3939", "2063-12-26", 33, 2),
("Artesanal Hormigon Camiseta", "29:022", "2096-03-26", 8, 2),
("Genérico Granito Teclado", "41:5959", "2027-05-11", 21, 1),
("Sorprendente Acero Ordenador", "56:1212", "2022-02-27", 4, 2),
("Práctico Metal Pizza", "30:2929", "2014-05-26", 19, 2),
("Rústico Granito Pelota", "24:099", "2080-11-18", 37, 1),
("Genérico Plástico Bicicleta", "01:4343", "2039-05-19", 45, 2),
("Genérico Acero Atún", "34:5959", "2099-10-07", 49, 2),
("Genérico Hormigon Pollo", "43:2020", "2097-11-10", 31, 1),
("Sabroso Algodón Queso", "44:1111", "2044-08-06", 8, 1),
("Fantástico Algodón Bacon", "20:5858", "2048-09-20", 21, 1),
("Fantástico Metal Patatas fritas", "08:1919", "2051-09-08", 37, 1),
("Increible Metal Raton", "47:5656", "2016-06-29", 40, 1),
("Hecho a mano Ladrillo Pantalones", "17:3939", "2010-03-16", 30, 1);

INSERT INTO estudiante(nombre, correo)
VALUES
("Armando", "MaraElena_Castillo34@yahoo.com"),
("Blanca", "Gilberto.Rocha@hotmail.com"),
("Alejandra", "Micaela_Moreno89@yahoo.com"),
("Roberto", "Julia.Oquendo39@hotmail.com"),
("Ana María", "Ana.Pedraza@hotmail.com"),
("Beatriz", "Gabriela_Murillo@yahoo.com"),
("Esperanza", "JosMara69@yahoo.com"),
("Mayte", "Gloria_Quesada@yahoo.com"),
("Santiago", "Gabriel48@yahoo.com"),
("María Elena", "Alicia_Ruelas@yahoo.com"),
("Antonio", "Cristbal35@hotmail.com"),
("Blanca", "Norma.Marrero@gmail.com"),
("Ernesto", "Francisco.Bustamante85@hotmail.com"),
("Adela", "LuisMiguel.Vzquez77@hotmail.com"),
("Norma", "MaraSoledad.Gaytn23@gmail.com"),
("Esteban", "Diana_Serrano@yahoo.com"),
("Gilberto", "Graciela_Venegas@hotmail.com"),
("Rosario", "Andrs.Valverde@yahoo.com"),
("Alfonso", "Manuel_Sedillo@hotmail.com"),
("José Emilio", "Anita.Carren16@gmail.com"),
("César", "Alfonso_Medina10@gmail.com"),
("Julia", "Catalina_Moya@yahoo.com"),
("Mateo", "Alfonso.Daz@hotmail.com"),
("Arturo", "Ramiro_Corral@yahoo.com"),
("Conchita", "MaradelCarmen_Ziga6@gmail.com"),
("Jorge", "Marta_Bentez@gmail.com"),
("Yolanda", "Samuel_Lucio@hotmail.com"),
("Lorenzo", "Ricardo.Dueas@gmail.com"),
("Leonor", "Dorotea.Murillo@hotmail.com"),
("Arturo", "Clemente17@hotmail.com"),
("Benjamín", "Felipe.Ruz66@yahoo.com"),
("Antonia", "Patricia68@yahoo.com"),
("Rubén", "JosMara89@gmail.com"),
("Marco Antonio", "Dolores_Haro@yahoo.com"),
("Josefina", "Natalia43@yahoo.com"),
("Sara", "Rosalia15@gmail.com"),
("Vicente", "Ester.Gastlum33@yahoo.com"),
("Luis Miguel", "Mariana_Brito57@yahoo.com"),
("Lola", "Alejandro_Anguiano94@gmail.com"),
("Conchita", "Mariano_Otero@yahoo.com"),
("Sara", "Federico.Esquivel@yahoo.com"),
("Felipe", "Graciela27@hotmail.com"),
("Teodoro", "Dbora_Carren@yahoo.com"),
("Pedro", "Pedro.Esquivel@hotmail.com"),
("Mateo", "Vicente_Camarillo67@gmail.com"),
("Raúl", "Elena_Palomino7@hotmail.com"),
("Laura", "Micaela_Otero84@gmail.com"),
("Francisca", "Juana_Cerda@hotmail.com"),
("Rubén", "Ernesto_Nieves5@yahoo.com"),
("Elisa", "Teresa53@gmail.com"),
("Sancho", "Juan_Vera@yahoo.com"),
("Eva", "Esperanza11@yahoo.com"),
("Florencia", "Mnica_Ojeda57@hotmail.com"),
("Hernán", "Francisca36@gmail.com"),
("Fernando", "Federico8@gmail.com"),
("Luz", "Carolina.Alba@yahoo.com"),
("Amalia", "MaraJos_Menndez71@hotmail.com"),
("Gabriela", "Gloria_Collazo43@gmail.com"),
("Ana María", "Samuel.Valencia8@yahoo.com"),
("María Teresa", "MaraTeresa.Zavala46@gmail.com"),
("Ricardo", "Natalia21@gmail.com"),
("Carlos", "Soledad.Heredia@hotmail.com"),
("Roberto", "Lourdes20@hotmail.com"),
("Mario", "Ernesto97@hotmail.com"),
("María José", "Homero58@gmail.com"),
("Blanca", "Jacobo6@yahoo.com"),
("José María", "Estela.Posada@hotmail.com"),
("Yolanda", "Samuel_Cortz@gmail.com"),
("Leonor", "Sonia21@yahoo.com"),
("Jacobo", "Juana.Canales@yahoo.com"),
("Isabel", "Elsa_Canales22@hotmail.com"),
("Conchita", "Felipe.Briones@hotmail.com"),
("Elvira", "Adela_Avils@hotmail.com"),
("Óscar", "Dbora_Laboy97@yahoo.com"),
("José Eduardo", "Rubn69@yahoo.com"),
("Carolina", "Nicols.Samaniego@hotmail.com"),
("Rosalia", "Bernardo61@yahoo.com"),
("Emilio", "Adn.Uras86@yahoo.com"),
("Sonia", "Germn7@hotmail.com"),
("Víctor", "Mario16@yahoo.com"),
("Eva", "Francisca.Barrios58@hotmail.com"),
("Mario", "JosEduardo47@yahoo.com"),
("Carmen", "Claudio.Guajardo@hotmail.com"),
("Margarita", "Catalina_Soliz@yahoo.com"),
("Horacio", "Arturo.Mireles51@hotmail.com"),
("Josefina", "Toms_Cervntez19@yahoo.com"),
("Federico", "LuisMiguel_Castillo@yahoo.com"),
("Patricia", "Homero62@yahoo.com"),
("Yolanda", "Alejandra.Quesada@gmail.com"),
("Manuela", "Adn.Cuellar87@yahoo.com"),
("Marisol", "Manuel_Zayas@gmail.com"),
("Francisca", "Ral.Fonseca73@yahoo.com"),
("Lola", "Federico6@hotmail.com"),
("Barbara", "Emilia98@hotmail.com"),
("César", "Esperanza_Briones53@yahoo.com"),
("María Teresa", "Manuela.Ramrez66@hotmail.com"),
("Diego", "Victoria25@hotmail.com"),
("María Elena", "Agustn_Meja78@hotmail.com"),
("Guillermo", "Lorenzo.Villaseor@yahoo.com"),
("Elisa", "Alicia.Alonso@yahoo.com");


INSERT INTO servicio_extension(id_facultad, id_profesor)
VALUES
(6, 1),
(8, 2),
(5, 3),
(4, 4),
(7, 5),
(5, 6),
(7, 7),
(7, 8),
(4, 9),
(3, 10),
(1, 11),
(1, 12),
(6, 13),
(8, 14),
(6, 15),
(1, 16),
(5, 17),
(5, 18),
(4, 19),
(5, 20),
(4, 21),
(3, 22),
(5, 23),
(2, 24),
(1, 25),
(8, 26),
(8, 27),
(2, 28),
(5, 29),
(3, 30),
(7, 31),
(6, 32),
(5, 33),
(7, 34),
(6, 35),
(2, 36),
(2, 37),
(4, 38),
(1, 39),
(6, 40),
(5, 41),
(6, 42),
(1, 43),
(3, 44),
(4, 45),
(4, 46),
(2, 47),
(7, 48),
(4, 49),
(6, 50);






INSERT INTO Tener_Profesor_Estudiante(profesor_id,estudiante_id)
VALUES
(32, 92),
(13, 74),
(12, 28),
(4, 43),
(27, 9),
(3, 68),
(35, 70),
(44, 43),
(11, 92),
(17, 95),
(48, 5),
(28, 35),
(8, 57),
(10, 56),
(47, 24),
(39, 73),
(41, 16),
(31, 38),
(36, 58),
(2, 79),
(44, 22),
(48, 16),
(36, 44),
(19, 28),
(46, 60),
(8, 62),
(44, 51),
(20, 33),
(35, 85),
(44, 93),
(2, 7),
(48, 73),
(13, 1),
(27, 20),
(30, 7),
(27, 14),
(12, 70),
(13, 32),
(43, 90),
(48, 55),
(28, 83),
(6, 89),
(12, 69),
(16, 73),
(20, 20),
(21, 23),
(23, 64),
(33, 78),
(18, 37),
(6, 29),
(27, 77),
(4, 3),
(29, 84),
(38, 2),
(31, 7),
(26, 78),
(2, 7),
(31, 99),
(29, 58),
(12, 87),
(19, 69),
(46, 28),
(34, 14),
(6, 49),
(13, 68),
(19, 50),
(30, 37),
(22, 28),
(46, 24),
(48, 51),
(45, 79),
(20, 80),
(21, 69),
(10, 7),
(6, 60),
(46, 4),
(22, 43),
(28, 20),
(38, 91),
(41, 96),
(12, 34),
(27, 84),
(14, 91),
(27, 50),
(23, 29),
(27, 46),
(13, 25),
(20, 94),
(19, 30),
(49, 50),
(25, 44),
(33, 87),
(23, 8),
(25, 79),
(34, 71),
(38, 63),
(26, 70),
(23, 54),
(38, 75),
(19, 19),
(28, 89),
(21, 10),
(2, 78),
(2, 63),
(34, 17),
(11, 58),
(40, 19),
(20, 27),
(24, 98),
(28, 31),
(16, 52),
(25, 22),
(21, 28),
(35, 30),
(49, 50),
(47, 80),
(36, 14),
(20, 44),
(47, 68),
(28, 75),
(33, 56),
(11, 3),
(45, 27),
(40, 63),
(1, 22),
(34, 78),
(16, 91),
(12, 7),
(42, 77),
(11, 82),
(7, 14),
(8, 61),
(43, 89),
(46, 62),
(39, 49),
(12, 51),
(8, 92),
(14, 36),
(5, 55),
(29, 69),
(43, 79),
(31, 60),
(24, 36),
(43, 17),
(28, 72),
(39, 3),
(31, 71),
(48, 73),
(25, 32),
(33, 7),
(26, 43),
(46, 92),
(37, 58),
(31, 79),
(22, 31),
(21, 25),
(2, 73),
(15, 95),
(29, 3),
(2, 21),
(46, 47),
(13, 41),
(38, 87),
(23, 20),
(47, 47),
(11, 20),
(4, 34),
(5, 80),
(23, 9),
(34, 51),
(4, 46),
(25, 26),
(48, 32),
(26, 63),
(13, 54),
(11, 91),
(20, 16),
(10, 83),
(43, 84),
(29, 88),
(35, 19),
(20, 72),
(14, 50),
(24, 47),
(23, 44),
(31, 44),
(20, 25),
(9, 93),
(10, 50),
(2, 10),
(16, 95),
(31, 54),
(14, 13),
(43, 37),
(21, 51),
(38, 56),
(41, 94),
(14, 23),
(23, 85),
(2, 62),
(49, 57),
(46, 79),
(22, 92),
(16, 48),
(19, 80),
(34, 2),
(12, 12),
(30, 62),
(37, 72),
(12, 92),
(29, 41),
(7, 99),
(28, 13),
(15, 61),
(49, 9),
(8, 67),
(50, 87),
(8, 2),
(50, 9),
(34, 88),
(28, 53),
(31, 99),
(36, 45),
(33, 73),
(3, 98),
(31, 39),
(22, 71),
(38, 41),
(33, 83),
(25, 73),
(23, 91),
(5, 28),
(16, 10),
(41, 75),
(3, 27),
(38, 16),
(21, 58),
(22, 84),
(4, 68),
(33, 10),
(5, 91),
(27, 36),
(14, 91),
(30, 3),
(13, 10),
(41, 66);



INSERT INTO cursar_estudiante_cursos
Values 
(34, 18, 31),
(31, 49, 30),
(43, 25, 19),
(83, 22, 11),
(8, 22, 43),
(52, 10, 5),
(89, 1, 33),
(32, 37, 29),
(50, 50, 24),
(71, 13, 45),
(19, 46, 15),
(59, 41, 27),
(31, 34, 4),
(64, 23, 30),
(19, 35, 44),
(1, 23, 26),
(48, 31, 8),
(57, 50, 39),
(34, 18, 21),
(2, 42, 6),
(90, 25, 49),
(72, 18, 37),
(65, 10, 14),
(16, 46, 1),
(77, 1, 7),
(28, 25, 25),
(13, 43, 12),
(9, 15, 19),
(35, 41, 45),
(74, 29, 47),
(60, 4, 1),
(2, 4, 16),
(44, 2, 6),
(77, 27, 47),
(99, 32, 45),
(87, 35, 28),
(7, 45, 8),
(64, 25, 22),
(86, 25, 48),
(76, 38, 42),
(50, 5, 36),
(30, 16, 21),
(87, 44, 5),
(37, 15, 14),
(79, 49, 34),
(74, 47, 9),
(40, 34, 26),
(54, 15, 13),
(46, 43, 49),
(70, 39, 15),
(99, 18, 1),
(11, 31, 8),
(92, 15, 5),
(95, 15, 46),
(38, 40, 18),
(31, 29, 29),
(59, 13, 18),
(15, 21, 23),
(36, 43, 32),
(11, 42, 49),
(30, 37, 29),
(82, 29, 19),
(66, 46, 5),
(56, 11, 22),
(36, 41, 22),
(15, 44, 37),
(37, 7, 39),
(5, 26, 17),
(37, 17, 19),
(51, 33, 22),
(77, 18, 47),
(1, 15, 27),
(92, 26, 34),
(64, 40, 50),
(92, 7, 43),
(92, 47, 37),
(80, 29, 37),
(72, 12, 16),
(9, 40, 33),
(49, 46, 34),
(83, 47, 18),
(41, 30, 32),
(70, 35, 21),
(7, 6, 28),
(41, 9, 10),
(92, 15, 16),
(9, 2, 43),
(1, 17, 3),
(84, 40, 7),
(37, 44, 43),
(93, 46, 18),
(4, 11, 21),
(76, 32, 9),
(69, 26, 11),
(30, 1, 43),
(9, 47, 43),
(65, 1, 18),
(95, 41, 29),
(34, 6, 1),
(86, 39, 12);



INSERT INTO pertenecer_sede_facultad VALUES
(2, 5),
(2, 6),
(1, 8),
(3, 7),
(1, 7),
(2, 3),
(4, 8),
(1, 5),
(1, 3),
(1, 3),
(2, 3),
(2, 1),
(1, 5),
(2, 8),
(4, 5),
(3, 2),
(1, 8),
(1, 5),
(4, 6),
(2, 1),
(3, 2),
(4, 8),
(2, 8),
(4, 1),
(3, 6),
(4, 4),
(3, 3),
(2, 3),
(4, 6),
(2, 4),
(3, 8),
(4, 8),
(3, 5),
(4, 3),
(2, 2),
(4, 7),
(3, 5),
(2, 5),
(3, 2),
(2, 5),
(1, 8),
(2, 4),
(1, 5),
(3, 2),
(4, 1),
(2, 7),
(4, 5),
(3, 3),
(2, 6),
(3, 4);


INSERT INTO Tener_Profesor_Estudiante VALUES
(49, 12),
(17, 78),
(27, 23),
(45, 7),
(35, 28),
(32, 73),
(14, 71),
(26, 85),
(32, 87),
(1, 94),
(23, 78),
(3, 11),
(15, 8),
(44, 20),
(36, 27),
(15, 57),
(48, 97),
(8, 38),
(27, 9),
(15, 36),
(35, 34),
(11, 52),
(34, 93),
(13, 91),
(8, 87),
(27, 51),
(28, 7),
(3, 30),
(19, 100),
(2, 38),
(17, 84),
(30, 50),
(12, 35),
(29, 9),
(3, 15),
(5, 34),
(26, 30),
(14, 17),
(29, 50),
(20, 39),
(24, 16),
(21, 83),
(43, 98),
(34, 86),
(15, 68),
(46, 13),
(23, 7),
(23, 39),
(26, 95),
(38, 47),
(6, 84),
(1, 41),
(38, 42),
(34, 93),
(35, 63),
(27, 42),
(1, 13),
(26, 64),
(33, 65),
(11, 83),
(14, 52),
(18, 58),
(8, 17),
(50, 87),
(43, 28),
(12, 81),
(32, 74),
(39, 74),
(35, 14),
(6, 9),
(17, 74),
(3, 45),
(50, 97),
(1, 81),
(42, 37),
(34, 21),
(33, 20),
(8, 74),
(27, 78),
(3, 55),
(35, 16),
(5, 75),
(1, 52),
(35, 50),
(33, 78),
(7, 8),
(44, 46),
(43, 34),
(44, 52),
(6, 13),
(20, 86),
(48, 48),
(27, 35),
(50, 2),
(40, 84),
(33, 36),
(8, 48),
(9, 27),
(5, 39),
(16, 3);


INSERT INTO cursar_estudiante_servicio VALUES
(48, 1, 7, 23),
(57, 39, 6, 1),
(90, 14, 5, 18),
(73, 11, 7, 9),
(64, 37, 6, 16),
(68, 44, 2, 11),
(80, 33, 5, 34),
(86, 10, 8, 29),
(15, 48, 7, 22),
(56, 3, 3, 14),
(79, 39, 8, 49),
(62, 20, 4, 4),
(85, 43, 4, 13),
(24, 30, 8, 12),
(71, 9, 1, 44),
(72, 11, 6, 41),
(50, 17, 7, 3),
(98, 9, 3, 32),
(69, 43, 3, 15),
(40, 19, 3, 33),
(84, 37, 8, 10),
(48, 19, 1, 22),
(55, 24, 8, 23),
(86, 42, 8, 47),
(15, 7, 8, 28),
(8, 3, 4, 37),
(15, 27, 3, 11),
(98, 3, 2, 11),
(59, 29, 3, 37),
(74, 19, 6, 18),
(75, 12, 1, 17),
(73, 1, 8, 39),
(7, 30, 1, 7),
(44, 19, 2, 21),
(93, 13, 6, 38),
(22, 23, 3, 27),
(94, 4, 8, 25),
(97, 19, 2, 15),
(33, 30, 8, 29),
(46, 42, 2, 9),
(33, 50, 1, 11),
(85, 26, 6, 23),
(64, 49, 5, 13),
(85, 33, 2, 44),
(4, 31, 3, 2),
(49, 37, 4, 9),
(86, 18, 7, 38),
(30, 9, 8, 45),
(87, 19, 4, 16),
(66, 33, 7, 26),
(8, 14, 2, 46),
(62, 23, 4, 5),
(40, 47, 7, 4),
(15, 4, 4, 15),
(3, 13, 5, 13),
(37, 18, 7, 47),
(79, 17, 8, 15),
(24, 19, 7, 47),
(68, 26, 6, 6),
(45, 8, 7, 4),
(16, 42, 3, 48),
(75, 24, 7, 36),
(63, 33, 3, 34),
(38, 10, 4, 37),
(31, 29, 4, 12),
(15, 22, 2, 26),
(80, 39, 2, 45),
(57, 5, 5, 21),
(44, 25, 1, 33),
(93, 30, 5, 29),
(18, 42, 4, 44),
(57, 27, 5, 41),
(34, 43, 7, 35),
(25, 22, 5, 36),
(17, 16, 1, 28),
(49, 21, 6, 48),
(85, 33, 7, 49),
(60, 46, 5, 7),
(60, 30, 6, 44),
(20, 2, 6, 4),
(45, 22, 5, 21),
(35, 14, 8, 14),
(95, 49, 2, 49),
(63, 20, 5, 30),
(79, 47, 7, 37),
(77, 9, 6, 16),
(57, 40, 7, 39),
(56, 33, 2, 41),
(12, 43, 6, 31),
(3, 3, 3, 47),
(43, 19, 7, 26),
(38, 12, 2, 13),
(3, 25, 3, 17),
(47, 48, 5, 47),
(82, 19, 1, 47),
(76, 47, 8, 12),
(31, 11, 7, 11),
(97, 5, 4, 21),
(29, 18, 7, 28),
(64, 39, 2, 45);


INSERT INTO entidad(tipo) VALUES
("Empresa"),
("Gobierno");


INSERT INTO practicas_pasantia (nombre,descripcion, tipo_empresa) VALUES
("Nacional Seguro Consultor", "Culpa laboriosam illum in quod. Explicabo voluptas quam sequi corrupti culpa adipisci distinctio recusandae modi. Dolorem perferendis possimus nam velit porro quod voluptates.", 2),
("Adelante Investigación Facilitador", "Sed recusandae facilis. Eum explicabo eos mollitia alias eaque totam occaecati. Officia reprehenderit fugiat iusto et doloremque. Vitae esse commodi eius tenetur rem totam dolor officiis. Ea atque cum veniam.", 2),
("Producto Aplicaciones Representante", "Quam a dicta vitae exercitationem culpa voluptas eos explicabo neque. Doloribus fugiat fugiat temporibus voluptatum saepe id quasi recusandae. Commodi porro nulla. Culpa quos earum accusamus repellendus iusto dolor ducimus. Et quis architecto alias.", 2),
("Dinánmico Normas Productor", "Magnam perferendis vitae sunt impedit esse dolores culpa in. Id libero nam accusantium voluptas. Consectetur blanditiis provident maxime porro nam aliquid odit.", 1),
("Central Operaciones Supervisor", "Sequi nulla itaque facere. Dicta inventore fugit at molestiae eos. Eos veniam cupiditate. Adipisci ratione optio atque facere. Quidem reiciendis ea vitae culpa incidunt.", 1),
("Producto Configuración Especialista", "Dignissimos voluptatibus reiciendis veniam. Quidem ullam ipsa dignissimos a qui accusantium fuga doloremque. Quas vitae iste. Fugiat voluptate aperiam sit earum reiciendis pariatur id praesentium.", 2),
("Inversor Intranet Planificador", "Quis maxime explicabo mollitia consequuntur ea. Quos ipsa voluptate. Reiciendis molestias porro perferendis. Voluptatibus aperiam rem quae dicta.", 1),
("Directo Aplicaciones Supervisor", "Molestias dolor incidunt distinctio molestiae maiores perspiciatis recusandae cum. Ab incidunt id at repellat exercitationem. Rerum inventore in veritatis voluptatum assumenda error. Saepe reiciendis aspernatur harum iure occaecati praesentium.", 2),
("Directo Marca Desarrollador", "Fugiat sit sint quidem facilis iusto odio iste sint. In mollitia molestias cupiditate illo quasi repellat. Maxime sed minima ullam velit ad consequatur voluptates quasi hic. Harum laboriosam est cumque voluptatem reiciendis sequi iste tempora. Sit a atque a.", 2),
("Directo Seguro Representante", "Eligendi mollitia hic cum aut amet ipsam ratione fugiat minus. Ab corrupti suscipit repellat ducimus ex ipsam perferendis ab ipsam. Temporibus inventore assumenda labore molestias excepturi nihil accusantium dolor sunt. Facere aut facilis reiciendis facere magnam incidunt. Necessitatibus similique rem saepe voluptate dicta. Eligendi vitae beatae dolorum laudantium cupiditate ipsa eum dolores.", 2),
("Corporativo Normas Arquitecto", "Impedit nobis possimus. Modi vitae veritatis. Maxime amet aliquid asperiores.", 2),
("Interno Tácticas Oficial", "Sint delectus eos inventore ad unde quibusdam nulla. Quod nostrum repellat. Esse vero a ut corporis. Reiciendis non ipsam nihil sunt voluptas voluptatem temporibus.", 2),
("Gerente Usabilidad Agente", "Nam deserunt quaerat alias quisquam. Vitae dolor iste molestias exercitationem officiis expedita soluta consectetur. Error incidunt quos. Cum ad aut ipsum magni soluta quia. Commodi qui enim unde amet.", 2),
("Adelante Optimización Oficial", "Officiis doloribus amet quis explicabo pariatur molestiae occaecati debitis. Nulla necessitatibus fuga sed. Laudantium enim ipsum corporis nulla enim voluptas. Officia aspernatur sapiente magni tempora ab esse repellat. Molestias perspiciatis non quos ipsam non animi explicabo quasi. Ipsum non error eligendi consequatur neque esse velit dolorum cum.", 2),
("Adelante Calidad Analista", "Labore beatae iusto dolorum consequuntur soluta. Est quo perferendis nemo. Atque tenetur sapiente culpa. Ratione saepe quam nulla odit mollitia mollitia. Nostrum doloremque molestiae ex rem. Ut corporis harum sapiente eius assumenda vero aliquid provident eius.", 1),
("Corporativo Tácticas Asistente", "Repudiandae cumque aut omnis voluptas veniam. Quidem dolorem quidem cumque expedita et ratione voluptatum odio esse. Eveniet veniam perspiciatis. Architecto voluptatibus eum aspernatur.", 2),
("Gerente Integración Director", "Mollitia aspernatur incidunt atque in doloremque magni. Delectus aperiam provident. Voluptas a natus quidem fugiat beatae exercitationem.", 2),
("Nacional Implementación Ejecutivo", "Dolore ducimus saepe esse ipsum veritatis facilis nobis eos labore. Nesciunt quo suscipit. Quasi ipsam ut provident laboriosam hic libero nulla iusto. Sunt repellat distinctio eveniet iure provident ut. Quasi error expedita cumque iusto provident neque deleniti.", 1),
("Director Optimización Agente", "Repellat autem similique magnam rerum placeat minus sequi laborum praesentium. Excepturi ullam doloremque doloribus. Facilis error tempore exercitationem nostrum voluptates. Reiciendis harum voluptatibus ullam error rerum occaecati. Velit quidem dignissimos dignissimos consequatur quam voluptatum rem.", 2),
("Producto Contabilidad Analista", "Neque iure molestiae incidunt vero porro harum. Et perspiciatis culpa officiis. Vitae aperiam delectus vel voluptatem consequatur voluptatibus dolores dolore. Modi sed hic molestiae blanditiis esse dolor voluptas. Nihil voluptates voluptatum facilis blanditiis alias nulla inventore sint deleniti.", 1),
("Global Configuración Técnico", "Laboriosam adipisci officia inventore omnis tenetur repudiandae aliquam ducimus dolores. Nihil voluptate rem cupiditate reprehenderit amet hic consequuntur eos aspernatur. Totam sit facere ea minima facilis ullam. Voluptas ab aliquid voluptatem.", 1),
("Jefe División Administrador", "Dolorem sequi dolorem hic ab voluptates commodi. Necessitatibus enim quasi quae sit. Animi laborum sit sequi cupiditate. Aliquid facilis aspernatur commodi mollitia nesciunt aliquam.", 1),
("International Seguro Consultor", "Tempore vitae nam cupiditate facilis veniam nobis. Ratione laudantium ratione culpa ex molestiae perferendis quibusdam velit asperiores. Perspiciatis pariatur accusantium occaecati cupiditate alias suscipit. Earum suscipit quos ad in earum. Non corporis sequi temporibus.", 2),
("Regional Tácticas Relacciones", "Dolorum perspiciatis ducimus voluptatem dolorem. Aliquid quo magnam dolor delectus. Magnam aspernatur vel pariatur nesciunt.", 2),
("Gerente Implementación Desarrollador", "Eaque tempore reiciendis officiis architecto explicabo at. Consectetur sit assumenda nihil facere sapiente. Necessitatibus optio illo illum nihil nisi consequuntur nihil autem ullam. Aspernatur veniam est.", 1),
("Dinánmico Integración Desarrollador", "Rerum temporibus tenetur maiores vero eum. Ipsa dolorum expedita porro ipsam quia quas eum dolorem. Culpa et porro inventore. Quasi asperiores consectetur dolor repudiandae.", 2),
("Directo Cuentas Oficial", "Rerum sequi nisi odit eius animi molestiae. Assumenda modi aspernatur sunt voluptate voluptatibus quae odit quasi ad. Vitae doloremque perspiciatis quae ullam incidunt eos itaque accusantium. Maiores illo esse. Voluptatem voluptas dolorem quisquam.", 1),
("Gerente Métricas Analista", "Inventore esse aut ipsam deleniti laudantium ipsa. Aliquam sunt et voluptatibus. Quae corrupti tempora repellat. Illo quaerat nostrum doloribus facilis porro eligendi. Ducimus animi consequuntur vitae impedit.", 2),
("Director Seguro Técnico", "Voluptatem alias perferendis nam rerum distinctio vero. Fugit animi recusandae et rem voluptas modi eos doloribus. Culpa vero architecto facilis.", 2),
("International Soluciones Especialista", "Dolores numquam occaecati minus eveniet quae deserunt. Soluta tempore dolores. Harum voluptas sint officiis natus harum minus quas ad. Quam pariatur ducimus iure. Numquam iure ipsam assumenda perferendis reprehenderit debitis laboriosam. Nemo minus molestiae vel debitis quasi impedit.", 2),
("Director División Asociado", "Ducimus non vitae dolorum eius est laborum corrupti optio minima. Expedita quod sequi nisi repellat ipsa molestiae maiores quas libero. Necessitatibus ipsam alias reiciendis voluptatibus impedit. Sequi quaerat impedit. Dolores explicabo alias culpa maxime repellendus iure. Molestiae aperiam laudantium laboriosam autem perspiciatis.", 1),
("Regional Métricas Desarrollador", "Repellat excepturi eum soluta deserunt occaecati delectus fugiat accusamus. Nihil fuga ex quibusdam ex doloribus similique porro. Vero ab saepe praesentium recusandae ipsum. Laborum dolorem tempora deserunt exercitationem doloribus praesentium. Distinctio quis eveniet soluta deserunt optio.", 2),
("Producto Mobilidad Oficial", "Eveniet id deleniti magnam ab facere rerum. Sed earum tenetur. Nisi delectus quidem sapiente.", 2),
("Jefe Marca Facilitador", "Ex tenetur sapiente soluta doloremque accusantium dolor ab sunt. Odit ex illum molestias odit quis tempora tempora adipisci. Vel expedita fuga dolor corrupti officiis ab consectetur pariatur dolore. Laboriosam dolore reiciendis dolorum iure eius porro exercitationem. Iusto vel nesciunt quas quasi.", 1),
("Corporativo Métricas Administrador", "Voluptatem reiciendis vero dolores unde veritatis ullam quasi soluta rerum. Quis labore nisi vitae dicta architecto. Necessitatibus delectus provident recusandae aut eos.", 2),
("Adelante Interacciones Gerente", "Repudiandae quo adipisci. Illo modi deleniti. Iure nam est molestias eos optio. Dolor voluptates hic cupiditate.", 2),
("Futuro Marketing Director", "Soluta neque quas dolorem tempore et. Nisi temporibus laudantium. Inventore reprehenderit tenetur officiis praesentium aspernatur.", 1),
("Global Tácticas Diseñador", "Consequatur magnam consequuntur libero dolor reiciendis natus natus quia temporibus. Voluptate explicabo ratione. Facilis nisi suscipit similique laborum vero fugiat. Doloribus dolorum nisi modi pariatur nesciunt minus fugit recusandae esse. Id eveniet ipsa quisquam iure dicta est beatae.", 1),
("Cliente Seguridada Coordinador", "Asperiores tempora iure maxime. Sed labore magni aspernatur quas sit. Occaecati in aut amet veniam unde facere.", 2),
("Distrito Métricas Ingeniero", "Voluptatibus facilis veritatis. Quam nemo incidunt eius quo quia quasi. Molestiae atque harum dolorem modi dolore necessitatibus maiores.", 1),
("Producto Usabilidad Analista", "Dolorem quas consequuntur repudiandae temporibus blanditiis sit beatae necessitatibus animi. Ab ab in quo eveniet. Libero nobis architecto. Cum tempore vitae explicabo voluptatum at. Sed accusamus corporis sequi.", 2),
("Senior Factores Consultor", "Minus aliquid dignissimos nisi est saepe veritatis fugit eveniet. Magni excepturi at at harum sed. Vel non excepturi dolor officiis dolores libero laboriosam. Ab quis ipsum. Aspernatur commodi in ullam qui facere officiis.", 2),
("Humano Respuesta Administrador", "Animi magni exercitationem excepturi a autem nisi nostrum. Earum cumque porro veniam. Velit quidem corporis eum ab minima qui rerum velit. Quia temporibus repellat excepturi id. Voluptatem sapiente dicta numquam ipsa non. Temporibus distinctio molestias ipsam numquam quasi esse rerum.", 1),
("Nacional Grupo Planificador", "Sit doloremque doloremque hic. Velit atque quos neque provident quas velit asperiores voluptates. Mollitia aliquid laboriosam repudiandae dignissimos consectetur molestias id aut aliquam. Fuga et suscipit sunt dolores deleniti quae fuga.", 1),
("Heredado Comunicaciones Técnico", "Tempora autem temporibus numquam repellendus aut placeat deleniti iste. Deserunt odio aut. Facilis neque enim impedit nostrum quam. Modi sit voluptas nihil eos. Nisi libero tenetur voluptatem facere aliquam impedit. Excepturi illum dignissimos corporis voluptas perspiciatis debitis quibusdam quia.", 2),
("Interno Paradigma Supervisor", "Quos ut eius. Fugit quis ab nesciunt porro unde officiis. Ex repellat sequi perspiciatis recusandae reprehenderit quas fugiat dolores incidunt. Aut enim dolore. Nemo eaque dignissimos maxime. Quibusdam recusandae et officiis aspernatur fugiat quidem explicabo nisi.", 1),
("Corporativo Contabilidad Coordinador", "Ad laborum quisquam laboriosam vel at ratione adipisci laudantium officia. Fuga quia sint optio harum nemo corrupti aperiam repellat. Numquam sed quo eos modi cum ut.", 2),
("Nacional Interacciones Técnico", "Quos perferendis dolorem quasi delectus sit at atque officia possimus. Sed tempora natus ducimus quas. Dignissimos ad iusto doloremque ipsam nobis delectus illum delectus velit.", 1),
("Humano Mobilidad Desarrollador", "Pariatur earum dolorum perspiciatis. Occaecati reprehenderit culpa commodi quo. Praesentium nam accusantium repellat error eum ipsum cumque mollitia.", 1),
("Nacional Paradigma Consultor", "Provident eius iure. Nostrum modi ea error facere id est excepturi tempora. Doloremque vel eius ducimus quaerat deserunt ab excepturi optio fugiat.", 2);

